name: Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    strategy:
      matrix:
        os:
          - linux
          - windows
        arch:
          - amd64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: 1.23
      config-file: .slsa/${{matrix.os}}-${{matrix.arch}}.yml
